export const PATHS = {
  HOME: "/",
  MODELS: "/models",
  MODEL: "/model/:modelId",
  LOCATIONS: "/locations",
  LOCATION: "/locations/:locationId",
  OFFERS: "/offers",
  CORPORATE: "/corporate",
  ABOUT: "/about",
  CONTACT: "/contact",
  HELP_CENTER: "/help",
  BOOKINGS: "/bookings",
  BOOKING: "/booking/:bookingId",
  CONFIRMATION: "/confirmation",
  LOGIN: "/login",
  SIGNUP: "/signup",
  CHECKOUT: "/checkout",
  PROFILE: "/profile",
  SETTINGS: "/settings",
  REVIEWS: "/reviews",
  NOTIFICATIONS: "/notifications",
};

export const ADMIN_PATHS = {
  DASHBOARD: "/admin",
  CARS: "/admin/cars",
  ADD_CAR: "/admin/cars/new",
  EDIT_CAR: "/admin/cars/:carId/edit",
  BOOKINGS: "/admin/bookings",
  USERS: "/admin/users",
  REPORTS: "/admin/reports",
  NOTIFICATIONS: "/admin/notifications",
};
